### ISSUE TITLE
Update from 1.25.0 to 1.26.0 causes NoClassDefFoundError on 'Preconditions'

### ISSUE THREAD

**Issue by geri-m** [googleapis/google-http-java-client#502]
#### Environment details

- OS: OSX 10.12.6
- Java version:  1.8.0_111-b14, 64 bit
- google-http-java-client version: 1.25.0/1.26.0

#### Steps to reproduce

1. The Statement ```Preconditions.checkState(true);``` works fine in 1.25.0.
2. Then switch to Version 1.26.0.
3. Now you will get a ```NoClassDefFoundError```
4. Then add guava (version 20.0) and everything is good again. 

#### Stacktrace

```
java.lang.NoClassDefFoundError: com/google/common/base/Preconditions

	at com.google.api.client.util.Preconditions.checkState(Preconditions.java:81)
	at org.soundtouch4j.ZoneApiTest.testPrecondition(ZoneApiTest.java:172)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
Caused by: java.lang.ClassNotFoundException: com.google.common.base.Preconditions
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 41 more
```

#### Any additional information below

Making sure to follow these steps will guarantee the quickest resolution possible.

In the class ```Preconditions``` there is a change from ```com.google.api.client.repackaged.com.google.common.base.Preconditions.checkArgument(expression);``` to ```com.google.common.base.Preconditions.checkArgument(expression); ```. And this package is not part of the JAR File.

**Comment by elharo** [comment]
1. Please do not use version ranges for reasons elaborated in https://github.com/GoogleCloudPlatform/cloud-opensource-java/blob/master/library-best-practices/JLBP-14.md

2. Guava doesn't fit the use case of a provided dependency. It should be explicit.

**Comment by garrettjonesgoogle** [comment]
@ejona86 might have context on why Guava is a provided dependency - do the original reasons for it still hold? With Guava's higher surface stability these days, I suspect the situation is different now.

**Comment by ejona86** [comment]
That's because Guava isn't actually a dependency at this level. It looks like it is supposed to be jarjar'd: https://github.com/googleapis/google-http-java-client/blob/master/google-http-client/pom.xml#L44

That said, I do remember that guava was an actual dependency _somewhere_ (maybe oauth?), because of all the guava-jdk5 nastiness, but I don't remember precisely where.
